# 端口
server:
  port: 8888
  address: 0.0.0.0

spring:
  application:
    name: weddingShow
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

  jackson:
    # 时间格式化
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl