spring:
  datasource:
    #测试环境
    url: jdbc:mysql://localhost:3306/wedding_show?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      max-lifetime: 30000
token:
  wechat:
    # 小程序配置
    mini-program:
      app-id: xxxxxxxxxxxxxxxxxxxxxxxxx
      app-secret: xxxxxxxxxxxxxxxxxxxxxxxxxx