# 端口
server:
  port: 8888
  address: 0.0.0.0

spring:
  application:
    name: weddingShow
  profiles:
    active: prod

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

  datasource:
    #测试环境
    url: jdbc:mysql://localhost:3306/wedding_show?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      max-lifetime: 30000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl